### PR TITLE
Pin Kubernetes version to previous one, latest crashes OpenShift client

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by goern** [comment]
@fridex

**Comment by vpavlin** [comment]
@goern He knows:)

**Comment by fridex** [comment]
Do you have logs to share? :)

**Comment by vpavlin** [comment]
@fridex No, the error basically was that OpenShift tried to instantiate Kubernetes client with parameter `async` whic has been probably removed, so I got exception

**Pull request merged**
